### ISSUE TITLE
OSError [Errno 31] Permission denied

### ISSUE THREAD

**Issue by glagnar** [okfn/docker-fiware-ckan#8]
I get an error while running the docker-compose.

```bash
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS                    PORTS                    NAMES
76db75b49b5c        dockerfiwareckan_ckan         "/usr/bin/supervisord"   About a minute ago   Up About a minute         0.0.0.0:8000->8000/tcp   dockerfiwareckan_ckan_1
f2ea4fdd8db7        solr:latest                   "docker-entrypoint..."   About a minute ago   Up About a minute         8983/tcp                 dockerfiwareckan_solr_1
585c250eea3a        dockerfiwareckan_datapusher   "/usr/bin/supervisord"   About a minute ago   Up About a minute         8000/tcp, 8800/tcp       dockerfiwareckan_datapusher_1
26878ba86296        postgres:latest               "docker-entrypoint..."   About a minute ago   Up About a minute         5432/tcp                 dockerfiwareckan_postgres_1
```

The services are running, but the CKAN instance gives an error.

```bash
[Thu Jun 01 11:08:41.677785 2017] [wsgi:error] [pid 25:tid 139839647827840]   File "/usr/local/lib/python2.7/os.py", line 150, in makedirs
[Thu Jun 01 11:08:41.677983 2017] [wsgi:error] [pid 25:tid 139839647827840]     makedirs(head, mode)
[Thu Jun 01 11:08:41.678002 2017] [wsgi:error] [pid 25:tid 139839647827840]   File "/usr/local/lib/python2.7/os.py", line 150, in makedirs
[Thu Jun 01 11:08:41.678022 2017] [wsgi:error] [pid 25:tid 139839647827840]     makedirs(head, mode)
[Thu Jun 01 11:08:41.678036 2017] [wsgi:error] [pid 25:tid 139839647827840]   File "/usr/local/lib/python2.7/os.py", line 157, in makedirs
[Thu Jun 01 11:08:41.678093 2017] [wsgi:error] [pid 25:tid 139839647827840]     mkdir(name, mode)
[Thu Jun 01 11:08:41.678118 2017] [wsgi:error] [pid 25:tid 139839647827840] OSError: [Errno 13] Permission denied: '/var/lib/ckan'
[Thu Jun 01 11:09:04.715764 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363] mod_wsgi (pid=24): Target WSGI script '/tmp/mod_wsgi-localhost:8000:33/handler.wsgi' cannot be loaded as Python module.
[Thu Jun 01 11:09:04.715797 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363] mod_wsgi (pid=24): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:8000:33/handler.wsgi'.
[Thu Jun 01 11:09:04.715818 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363] Traceback (most recent call last):
[Thu Jun 01 11:09:04.715831 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/tmp/mod_wsgi-localhost:8000:33/handler.wsgi", line 94, in <module>
[Thu Jun 01 11:09:04.715856 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     recorder_directory=recorder_directory)
[Thu Jun 01 11:09:04.715864 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/site-packages/mod_wsgi/server/__init__.py", line 1267, in __init__
[Thu Jun 01 11:09:04.715882 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     exec(code, self.module.__dict__)
[Thu Jun 01 11:09:04.715899 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/srv/app/ckan.wsgi", line 8, in <module>
[Thu Jun 01 11:09:04.715913 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     application = loadapp('config:%s' % config_filepath)
[Thu Jun 01 11:09:04.715921 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Thu Jun 01 11:09:04.715935 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     return loadobj(APP, uri, name=name, **kw)
[Thu Jun 01 11:09:04.715950 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Thu Jun 01 11:09:04.715962 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     return context.create()
[Thu Jun 01 11:09:04.715968 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Thu Jun 01 11:09:04.715987 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     return self.object_type.invoke(self)
[Thu Jun 01 11:09:04.715994 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Thu Jun 01 11:09:04.716004 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Thu Jun 01 11:09:04.716019 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
[Thu Jun 01 11:09:04.716031 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     val = callable(*args, **kw)
[Thu Jun 01 11:09:04.716039 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 48, in make_app
[Thu Jun 01 11:09:04.716069 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     **app_conf)
[Thu Jun 01 11:09:04.716170 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/srv/app/src/ckan/ckan/config/middleware/pylons_app.py", line 148, in make_pylons_stack
[Thu Jun 01 11:09:04.716192 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     os.makedirs(path)
[Thu Jun 01 11:09:04.716212 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/os.py", line 150, in makedirs
[Thu Jun 01 11:09:04.716455 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     makedirs(head, mode)
[Thu Jun 01 11:09:04.716463 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/os.py", line 150, in makedirs
[Thu Jun 01 11:09:04.716472 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     makedirs(head, mode)
[Thu Jun 01 11:09:04.716478 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]   File "/usr/local/lib/python2.7/os.py", line 157, in makedirs
[Thu Jun 01 11:09:04.716487 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363]     mkdir(name, mode)
[Thu Jun 01 11:09:04.716504 2017] [wsgi:error] [pid 24:tid 139839368808192] [remote 172.17.0.1:59363] OSError: [Errno 13] Permission denied: '/var/lib/ckan'
172.17.0.1 - - [01/Jun/2017:11:09:04 +0000] "GET / HTTP/1.1" 500 531
```

**Comment by amercader** [comment]
This was fixed by b24aa67df9a0658e5c74261bce0f29ad152e8499
